// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1WT_xiBSbQ1Ky41jVcf3g7_pagpO7Wac',
    appId: '1:987180946645:web:ba4f18aa65f24c20e7be5c',
    messagingSenderId: '987180946645',
    projectId: 'example-8418d',
    authDomain: 'example-8418d.firebaseapp.com',
    storageBucket: 'example-8418d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyp_cA36NfZ1c-DQggUmVIS-3k-F7AOGs',
    appId: '1:987180946645:android:9981e1d0e5b51de2e7be5c',
    messagingSenderId: '987180946645',
    projectId: 'example-8418d',
    storageBucket: 'example-8418d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrbLeIShnYg-EIXHAo9Jf6BY_U-TlIUrU',
    appId: '1:987180946645:ios:c149537c70f3f5ebe7be5c',
    messagingSenderId: '987180946645',
    projectId: 'example-8418d',
    storageBucket: 'example-8418d.appspot.com',
    iosClientId: '987180946645-eiaubnak3shjaelve35acf9iurkab92v.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1WT_xiBSbQ1Ky41jVcf3g7_pagpO7Wac',
    appId: '1:987180946645:web:39ecf9f592ca8636e7be5c',
    messagingSenderId: '987180946645',
    projectId: 'example-8418d',
    authDomain: 'example-8418d.firebaseapp.com',
    storageBucket: 'example-8418d.appspot.com',
  );
}
